# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://petaren.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Petar; a blog
  avatar: avatar.png
  gravatar: f5be4affd9bdec155863e5b093c25dff
  description: "A blog about iOS development, swift, objective-c and linux" # used by search engines

  # Header and footer text
  header_text: >
     A blog about iOS development, swift, objective-c and linux
  header_text_feature_image: "img/blog-header.jpg"
  footer_text: #>
   #Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: petar@petar.se
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "petaren"
  google_plus:
  instagram:
  linkedin: "http://se.linkedin.com/in/petaren"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "naw"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-61388303-1
  disqus_shortname:
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
sass:
  sass_dir: _sass
  style: :compressed
